### ISSUE TITLE
`MFEKmetadata v0.0.2-beta1:` binary executable not working on MacOS 11.6? `zsh: exec format error`

### ISSUE THREAD

**Issue by eliheuer** [MFEK/metadata#49]
I tried [downloading a MFEKmetadata binary](https://github.com/MFEK/metadata/releases/tag/v0.0.2b1) to use with [glif2svg](https://github.com/MFEK/glif2svg), but I can't figure out how to get it working on MacOS 11.6.

I did:

```
$ chmod +x MFEKmetadata
```

Then: 

```
$ ./MFEKmetadata
```

Gives me: 

```
zsh: exec format error: ./MFEKmetadata
```

**Comment by ctrlcctrlv** [comment]
Probably not a bug as that page says…

> **(Mac users: Please download from "Actions" tab or compile. Sorry for the inconvenience.)**

The non-Windows executable provided there is—

```
/home/fred/Downloads/MFEKmetadata: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=45381f456270a15b16b94bdbbe7e0c299058bc37, for GNU/Linux 4.4.0, with debug_info, not stripped
```

It might be a bug that I have no way to build MacOS binaries without GH Actions, but that'd be a different bug, not this bug.
